import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'RestauManage',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="es" className='light'>
      <head>
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
      </head>
        <body className={inter.className}>
          <Providers>
            {children}
          </Providers>
        </body>
    </html>
  )
}
