import { Inter } from 'next/font/google'
import './globals.css'
import { headers } from 'next/headers'
import { Providers } from './providers'
import Header from './components/header'
import Sidebar from './components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'RestauManage',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  const fullPathname = headers().get('x-url').split('/')

  const noLayout = fullPathname.includes('login') || fullPathname.includes('register')

  return (
    <html lang="es" className='light'>
      <head>
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
      </head>
      <body className={`${inter.className} bg-grey-50`}>
      <div className="flex min-h-screen">
        {!noLayout && <Sidebar />}
        <div className="flex flex-col flex-1">
          {!noLayout && <Header />}
          <div className="flex-1">
            <Providers>
              {children}
            </Providers>
          </div>
        </div>
      </div>
    </body>
    </html>
  )
}
